# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  image.version.major: '2'
  image.version.minor: '1'
  image.version: '$(image.version.major).$(image.version.minor).1'
  image.basename: 'npn_webserver'
  image.name: '$(image.basename):$(build.buildId)'
  image.tagversion: '$(image.basename):$(image.version)'
  image.taglatest: '$(image.basename):latest'

steps:
- script: |
    docker build -f Dockerfile -t $(image.name)-dev . --target=devel-env
    docker login -u $(dockerId) -p $(dockerPassword)
    docker tag $(image.name)-dev $(dockerRepoId)/$(image.basename):dev-$(build.buildId)
    docker tag $(image.name)-dev $(dockerRepoId)/$(image.basename):dev-latest
    docker push $(dockerRepoId)/$(image.basename):dev-$(build.buildId)
    docker push $(dockerRepoId)/$(image.basename):dev-latest
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/devel')
  displayName: 'build devel image and push to docker'
- script: docker build -f Dockerfile -t $(image.name) .
  displayName: 'build image'
- script: |
    docker run -t $(image.name) nginx -v
    docker run -t $(image.name) npm -v
    docker run -t $(image.name) node -v
    docker run -t $(image.name) php -v
  displayName: 'validate built image'
- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker tag $(image.name) $(dockerRepoId)/$(image.tagversion)
    docker tag $(image.name)$(dockerRepoId)/$(image.basename):$(image.version.major).$(image.version.minor)
    docker tag $(image.name) $(dockerRepoId)/$(image.taglatest)
    docker push $(dockerRepoId)/$(image.tagversion)
    docker push $(dockerRepoId)/$(image.basename):$(image.version.major).$(image.version.minor)
    docker push $(dockerRepoId)/$(image.taglatest)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'push image to dockerhub'
